/// <reference types="astro/client" />

// Worker binding types — Cloudflare.Env and the `cloudflare:workers` module —
// are generated by `wrangler types` into ../../worker-configuration.d.ts
// (checked in; the build regenerates it). This file only declares the secrets
// that aren't in wrangler.jsonc.

/* eslint-disable @typescript-eslint/consistent-type-definitions */

declare namespace Cloudflare {
  interface Env {
    /** Sentry DSN for server-side error reporting. Unset → Sentry is inert.
     *  Set as a secret on the Worker, not committed (OSS repo). */
    SENTRY_DSN?: string;
  }
}

interface ImportMetaEnv {
  readonly PUBLIC_API_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
