/// <reference types="astro/client" />

// Worker binding types — Cloudflare.Env and the `cloudflare:workers` module —
// are generated by `wrangler types` into ../../worker-configuration.d.ts
// (checked in; the build regenerates it). This file only declares app locals
// and the secrets that aren't in wrangler.jsonc.

/* Interfaces (not type aliases) so the declarations merge with the generated
 * and adapter-provided ones. */
/* eslint-disable @typescript-eslint/consistent-type-definitions */

declare namespace Cloudflare {
  interface Env {
    /** Sentry DSN for server-side error reporting. Unset → Sentry is inert.
     *  Set as a secret on the Worker, not committed (OSS repo). */
    SENTRY_DSN?: string;
  }
}

declare namespace App {
  interface Locals {
    /** The page's language, validated against the whitelist (pages only). */
    lang?: string;
    /** The enabled languages, resolved once per request (pages only). */
    languages?: SiteLanguage[];
  }

  /** An enabled language from the whitelist (see @hiroba/db languages). */
  interface SiteLanguage {
    code: string;
    label: string;
    nativeLabel: string;
  }
}

interface ImportMetaEnv {
  readonly API_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
